# === ESTÁGIO 1: COMPILAÇÃO ===
FROM node:20-slim AS builder

WORKDIR /app

# Copia os manifestos e instala as dependências
COPY package*.json ./
RUN npm install

# Copia o resto dos arquivos e gera a pasta de produção (/app/dist)
COPY . .
RUN npm run build

# === ESTÁGIO 2: SERVIDOR DE PRODUÇÃO ===
FROM nginx:alpine

# Remove as configurações padrões do Nginx para não dar conflito
RUN rm -rf /usr/share/nginx/html/*

# Copia a configuração customizada do Nginx para o container
COPY default.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos compilados do estágio anterior para a pasta do Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Expõe a porta padrão do Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


