# Generated by Django 6.0.3 on 2026-04-20 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Fisica', 'Pessoa Física'), ('Juridica', 'Pessoa Jurídica')], default='Fisica', max_length=10)),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('contato_geral', models.CharField(max_length=255)),
                ('endereco_completo', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_funcao', models.CharField(max_length=100)),
                ('user_setor', models.CharField(max_length=100)),
                ('user_data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa_prestadora', models.CharField(max_length=100)),
                ('nome_negocio', models.CharField(max_length=200)),
                ('solicitante', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_prevista_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_final', models.DateField(blank=True, null=True)),
                ('arquivo_documento', models.FileField(blank=True, null=True, upload_to='documentos_negocios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='ComercialApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('local_execucao', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('embarcacao', models.CharField(max_length=100)),
                ('porto', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ComercialApp.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComercialApp.user'),
        ),
    ]
