# Generated by Django 6.0.3 on 2026-05-23 23:14

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Fisica', 'Pessoa Física'), ('Juridica', 'Pessoa Jurídica')], default='Fisica', max_length=10)),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('contato_geral', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_completo', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('empresa_nome', models.CharField(default='Linave ERP', max_length=150)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa_prestadora', models.CharField(max_length=100)),
                ('nome_negocio', models.CharField(max_length=200)),
                ('solicitante', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('Planejamento', 'Planejamento'), ('Negociação', 'Negociação'), ('Em Andamento', 'Em Andamento'), ('Finalização', 'Finalização')], default='Planejamento', max_length=30)),
                ('status', models.CharField(default='Aguardando orçamento', max_length=50)),
                ('orcamento_realizado', models.BooleanField(default=False)),
                ('requer_reorcamento', models.BooleanField(default=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_prevista_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_final', models.DateField(blank=True, null=True)),
                ('arquivo_documento', models.FileField(blank=True, null=True, upload_to='documentos_negocios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='ComercialApp.cliente')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='ComercialApp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Levantamento',
            fields=[
                ('id_orcamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orcamentos', to='ComercialApp.cliente')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio_orcamento', to='ComercialApp.negocio')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levantamentos', to='ComercialApp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observacoes_setor_orcamento', models.TextField(blank=True, null=True)),
                ('numero_orcamento', models.CharField(blank=True, max_length=100)),
                ('versao', models.CharField(blank=True, default='A', max_length=10)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('data_recusa', models.DateField(blank=True, null=True)),
                ('levantamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_levantamento', to='ComercialApp.levantamento')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='ComercialApp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MDO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fnc', models.CharField(max_length=100)),
                ('qnt', models.IntegerField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('custo_unit_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_de_obra', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=10)),
                ('qnt', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('terceirizado', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ativ_prevista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atividade', models.CharField(max_length=200)),
                ('duracao', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Planilhas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colunas', models.CharField(max_length=255)),
                ('linhas', models.JSONField(blank=True, default=list)),
                ('escopo_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escopo_planilhas', to='ComercialApp.escopo')),
            ],
        ),
        migrations.CreateModel(
            name='PropostaComercial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('numero_proposta', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('motivo_recusa', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=200)),
                ('saudacao', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('texto_de_abertura', models.TextField()),
                ('responsabilidade_contratada', models.CharField(max_length=150)),
                ('responsabilidade_contratante', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicoes_gerais', models.TextField()),
                ('condicoes_pagamento', models.TextField()),
                ('prazo', models.CharField(max_length=100)),
                ('encerramento', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_propostas', to='ComercialApp.cliente')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocio_propostas', to='ComercialApp.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='escopo',
            name='proposta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_escopo', to='ComercialApp.propostacomercial'),
        ),
        migrations.CreateModel(
            name='Resumo_orcamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impostos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qnt', models.IntegerField()),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('local_execucao', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('embarcacao', models.CharField(max_length=100)),
                ('porto', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ComercialApp.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='escopo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopo_servico', to='ComercialApp.servico'),
        ),
        migrations.CreateModel(
            name='Servico_terceirizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=10)),
                ('qnt', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.CharField(max_length=250)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceirizados', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_os', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('projeto', models.CharField(blank=True, max_length=200)),
                ('equipamento', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('cc', models.CharField(blank=True, max_length=50)),
                ('data_inicio_previsto', models.DateField()),
                ('data_termino_previsto', models.DateField()),
                ('supervisor_encarregado', models.CharField(max_length=150)),
                ('descricao_geral_servico', models.TextField()),
                ('a_ser_incluido', models.JSONField(blank=True, default=dict)),
                ('mao_obra', models.JSONField(blank=True, default=dict)),
                ('horas_trabalhadas_servico', models.JSONField(blank=True, default=list)),
                ('status_os', models.CharField(choices=[('rascunho', 'Rascunho'), ('emproducao', 'Em Produção'), ('concluida', 'Concluída')], default='rascunho', max_length=20)),
                ('status_envio', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada')], default='pendente', max_length=20)),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada')], default='pendente', max_length=20)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('documento_assinatura_aprovacao', models.FileField(blank=True, null=True, upload_to='documentos_os_assinatura/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='ComercialApp.cliente')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='ComercialApp.negocio')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OS', to='ComercialApp.workspace')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='ComercialApp.workspace'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_funcao', models.CharField(max_length=100)),
                ('user_setor', models.CharField(max_length=100)),
                ('user_data_nascimento', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ComercialApp.workspace')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
