# Generated by Django 6.0.3 on 2026-04-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cnpj', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origem_lead', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitante', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('responsavel_comercial', models.CharField(max_length=150)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='ComercialApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem_servico_id', models.BigIntegerField(blank=True, null=True)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('embarcacao', models.CharField(max_length=100)),
                ('local_execucao', models.CharField(max_length=150)),
                ('porto', models.CharField(max_length=100)),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10)),
                ('prazo_desejado', models.DateField()),
                ('descricao_solicitacao', models.TextField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ComercialApp.negocio')),
            ],
        ),
    ]
