# Generated by Django 6.0.3 on 2026-05-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo_orcamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impostos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Levantamento',
            fields=[
                ('id_orcamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orcamentos', to='ComercialApp.cliente')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio_orcamento', to='ComercialApp.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Observacoes_setor_orcamento', models.TextField(blank=True, null=True)),
                ('levantamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_levantamento', to='ComercialApp.levantamento')),
                ('resumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_resumo', to='ComercialApp.resumo_orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='MDO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fnc', models.CharField(max_length=100)),
                ('qnt', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('custo_unit_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_de_obra', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terceirizado', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ativ_prevista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atividade', models.CharField(max_length=200)),
                ('duração', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ComercialApp.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Servico_terceirizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(max_length=250)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceirizados', to='ComercialApp.orcamento')),
            ],
        ),
    ]
