# Generated by Django 6.0.3 on 2026-05-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='workspace',
        ),
    ]
