# Generated by Django 6.0.3 on 2026-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=150)),
                ('user_funcao', models.CharField(max_length=100)),
                ('user_setor', models.CharField(max_length=100)),
                ('user_data_nascimento', models.DateField()),
            ],
        ),
    ]
