# Generated by Django 6.0.3 on 2026-05-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0002_remove_cliente_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='config',
            new_name='data',
        ),
    ]
