# Generated by Django 5.2.14 on 2026-06-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0002_alter_material_qnt_alter_mdo_dias_alter_mdo_qnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativ_prevista',
            name='duracao',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resumo_orcamento',
            name='qnt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
