# Generated by Django 6.0.3 on 2026-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0002_proposta_preco_colunas_ocultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='numero_customizado',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
