# Generated by Django 6.0.3 on 2026-05-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0002_resumo_orcamento_levantamento_orcamento_mdo_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_os', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('projeto', models.CharField(blank=True, max_length=200)),
                ('equipamento', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('cc', models.CharField(blank=True, max_length=50)),
                ('data_inicio_previsto', models.DateField()),
                ('data_termino_previsto', models.DateField()),
                ('supervisor_encarregado', models.CharField(max_length=150)),
                ('descricao_geral_servico', models.TextField()),
                ('a_ser_incluido', models.JSONField(blank=True, default=dict)),
                ('mao_obra', models.JSONField(blank=True, default=dict)),
                ('status_os', models.CharField(choices=[('rascunho', 'Rascunho'), ('emproducao', 'Em Produção'), ('concluida', 'Concluída')], default='rascunho', max_length=20)),
                ('status_envio', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada')], default='pendente', max_length=20)),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada')], default='pendente', max_length=20)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('documento_assinatura_aprovacao', models.FileField(blank=True, null=True, upload_to='documentos_os_assinatura/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='ComercialApp.cliente')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='ComercialApp.negocio')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
    ]
