# Generated by Django 6.0.3 on 2026-04-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
