# Generated by Django 5.2.14 on 2026-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0003_alter_ativ_prevista_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostacomercial',
            name='assunto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='condicoes_gerais',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='condicoes_pagamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='prazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='referencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='responsabilidade_contratada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='responsabilidade_contratante',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='saudacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='texto_de_abertura',
            field=models.TextField(blank=True, default=''),
        ),
    ]
