# Generated by Django 6.0.3 on 2026-09-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0003_negocio_numero_customizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('negocio', 'Documento do Negócio'), ('cliente_assinado', 'Documento assinado pelo cliente'), ('os_assinatura', 'Assinatura/aprovação de OS'), ('orcamento_importado', 'Orçamento anexado na importação do negócio'), ('proposta_importada', 'Proposta anexada na importação do negócio'), ('fin_anexo', 'Anexo financeiro'), ('fin_comprovante', 'Comprovante de pagamento'), ('fin_documento', 'Documento de compra (NF entrada/boleto)'), ('outro', 'Outro')], default='outro', max_length=40),
        ),
    ]
