# Generated by Django 6.0.3 on 2026-05-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0005_ordenservico_horas_trabalhadas_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopo_servico', to='ComercialApp.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Planilhas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colunas', models.CharField(max_length=255)),
                ('linhas', models.JSONField(blank=True, default=list)),
                ('escopo_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escopo_planilhas', to='ComercialApp.escopo')),
            ],
        ),
        migrations.CreateModel(
            name='PropostaComercial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=200)),
                ('saudacao', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('texto_de_abertura', models.TextField()),
                ('responsabilidade_contratada', models.CharField(max_length=150)),
                ('responsabilidade_contratante', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicoes_gerais', models.TextField()),
                ('condicoes_pagamento', models.TextField()),
                ('prazo', models.CharField(max_length=100)),
                ('encerramento', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_propostas', to='ComercialApp.cliente')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocio_propostas', to='ComercialApp.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='escopo',
            name='proposta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_escopo', to='ComercialApp.propostacomercial'),
        ),
    ]
