# Generated by Django 6.0.3 on 2026-05-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0005_ordenservico_horas_trabalhadas_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='categoria',
            field=models.CharField(choices=[('Planejamento', 'Planejamento'), ('Negociação', 'Negociação'), ('Em Andamento', 'Em Andamento'), ('Finalização', 'Finalização')], default='Planejamento', max_length=30),
        ),
    ]
