# Generated by Django 6.0.3 on 2026-09-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0005_alter_documento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='criado_por_cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='criado_por_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='criado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por_cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
