# Generated by Django 6.0.3 on 2026-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0006_negocio_criado_por_cpf_negocio_criado_por_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('negocio', 'Documento do Negócio'), ('cliente_assinado', 'Documento assinado pelo cliente'), ('os_assinatura', 'Assinatura/aprovação de OS'), ('orcamento_importado', 'Orçamento anexado na importação do negócio'), ('proposta_importada', 'Proposta anexada na importação do negócio'), ('almoxarifado_imagem', 'Imagem de item do almoxarifado'), ('almoxarifado_manutencao_entrada', 'Foto de entrada em manutenção'), ('almoxarifado_manutencao_saida', 'Foto de saída da manutenção'), ('fin_anexo', 'Anexo financeiro'), ('fin_comprovante', 'Comprovante de pagamento'), ('fin_documento', 'Documento de compra (NF entrada/boleto)'), ('outro', 'Outro')], default='outro', max_length=40),
        ),
    ]
