# Generated by Django 6.0.3 on 2026-05-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0006_escopo_planilhas_propostacomercial_and_more'),
        ('ComercialApp', '0006_negocio_categoria'),
    ]

    operations = [
    ]
