# Generated by Django 6.0.3 on 2026-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0007_merge_20260514_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativ_prevista',
            old_name='duração',
            new_name='duracao',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='Observacoes_setor_orcamento',
            new_name='observacoes_setor_orcamento',
        ),
        migrations.AddField(
            model_name='negocio',
            name='orcamento_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='requer_reorcamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='status',
            field=models.CharField(default='Aguardando orçamento', max_length=50),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
