# Generated by Django 6.0.3 on 2026-05-20 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0008_rename_duração_ativ_prevista_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_recusa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero_orcamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='versao',
            field=models.CharField(blank=True, default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='numero_proposta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
    ]
