# Generated by Django 6.0.3 on 2026-05-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0007_merge_20260514_1505'),
        ('ComercialApp', '0009_orcamento_data_criacao_orcamento_data_recusa_and_more'),
    ]

    operations = [
    ]
