# Generated by Django 6.0.3 on 2026-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0011_alter_material_custo_unitario_alter_material_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contato_geral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_completo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
