# Generated by Django 6.0.3 on 2026-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialApp', '0012_alter_cliente_contato_geral_alter_cliente_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='quantidade',
            new_name='qnt',
        ),
        migrations.RenameField(
            model_name='servico_terceirizado',
            old_name='custo_unit',
            new_name='valor_unit',
        ),
        migrations.RemoveField(
            model_name='material',
            name='custo_unitario',
        ),
        migrations.RemoveField(
            model_name='servico_terceirizado',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='material',
            name='custo_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servico_terceirizado',
            name='qnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
