from django.db import models

class Cliente(models.Model):
    TIPO_CHOICES = [('Fisica', 'Pessoa Física'), ('Juridica', 'Pessoa Jurídica')]
    STATUS_CHOICES = [('Ativo', 'Ativo'), ('Inativo', 'Inativo')]

    id = models.BigAutoField(primary_key=True)
    tipo = models.CharField(max_length=10, choices=TIPO_CHOICES, default='Fisica')
    razao_social = models.CharField(max_length=150) # "Razão Social / Nome Completo"
    nome_fantasia = models.CharField(max_length=150, null=True, blank=True)
    documento = models.CharField(max_length=20, unique=True) # CPF ou CNPJ
    inscricao_estadual = models.CharField(max_length=20, null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='Ativo')
    contato_geral = models.CharField(max_length=255) 
    endereco_completo = models.TextField()
    data_cadastro = models.DateField(auto_now_add=True)
    usuario_responsavel = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'Razão Social: {self.razao_social}'


class Negocio(models.Model):
    id = models.BigAutoField(primary_key=True)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE, related_name='negocios')
    empresa_prestadora = models.CharField(max_length=100) 
    nome_negocio = models.CharField(max_length=200) 
    solicitante = models.CharField(max_length=150)
    cargo = models.CharField(max_length=100, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=254)
    data_solicitacao = models.DateField(auto_now_add=True)
    data_prevista_inicio = models.DateField(null=True, blank=True)
    data_prevista_final = models.DateField(null=True, blank=True)
    arquivo_documento = models.FileField(upload_to='documentos_negocios/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nome_negocio} - {self.cliente.razao_social}"

class Servico(models.Model):
    id = models.BigAutoField(primary_key=True)
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, related_name='servicos')
    tipo_servico = models.CharField(max_length=100) 
    categoria = models.CharField(max_length=100)    
    local_execucao = models.CharField(max_length=150) 
    descricao = models.TextField()                 
    embarcacao = models.CharField(max_length=100)
    porto = models.CharField(max_length=100, null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.tipo_servico} - {self.embarcacao}"
    
class User(models.Model):
    user_email = models.CharField(max_length=150, primary_key=True)
    user_name = models.CharField(max_length=200)
    user_funcao = models.CharField(max_length=100)
    user_setor = models.CharField(max_length=100)
    user_data_nascimento = models.DateField()
    
    def __str__(self):
        return f"E-mail: {self.user_email} - Nome: {self.user_name} - Função: {self.user_funcao} - Setor: {self.user_setor}"

#--------------------- Orçamento ------------------

class Levantamento(models.Model):
    #External not displayed attributes:
    id_orcamento = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
        #auto-fill / pulled from another table entry
    cliente = models.ForeignKey(Cliente, editable=False, on_delete=models.CASCADE, related_name='cliente_orcamentos') # client id listed on selected negocio entry , auto-filled from negocio data
    negocio = models.OneToOneField(Negocio, editable=False, on_delete=models.CASCADE, related_name='negocio_orcamentos') # negocio id which this orcamento is about, to be selected from a dropdown list of existing negocio entries
    solicitante = models.ForeignKey(User, editable=False, on_delete=models.PROTECT, related_name='user_orcamentos') # user name logged in and creating the orcamento, auto-filled from user data
    @property
    def responsavel_financeiro(self):
        """
        Returns the soliciter from the associated Business.
        """
        return self.negocio.solicitante
    @property
    def dados_servicos(self):
        """Pulls all services linked to the specific business deal."""
        # This uses the 'servicos' related_name you defined in your Servico model
        return self.negocio.servicos.all()

    @property
    def arquivos_negocio(self):
        """Accesses the file attached to the business deal."""
        return self.negocio.arquivo_documento

    orcamento_link = models.OneToOneField("Orcamento", on_delete=models.CASCADE, related_name='levantamento_orcamento', null=True, blank=True) # link to the Resumo_orcamento entry that contains the economic summary of this orçamento
    def __str__(self):
        return f"Orçamento {self.id_orcamento} - Negócio {self.negocio.id} - Solicitante: {self.solicitante.user_name}"

class MDO(models.Model): #Mão de obra
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    fnc = models.CharField(max_length=100) # free text field to specify the role or function of the labor
    qnt = models.IntegerField() # field to specify the quantity of labor units required
    dias = models.IntegerField() # field to specify the number of days required for the labor
    custo_unit = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the cost of the labor per unit per day
    valor_total = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the total cost of the labor (quantidade * dias * custo)
    observacao = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the labor
    
    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="mao_de_obra_resumo") # link to the Resumo_orcamento entry that this MDO entry is part of, to be selected from a dropdown list of existing Resumo_orcamento entries
    def __str__(self):
        return f"Mão de Obra {self.id} - Custo: {self.valor_total}"

class Ativ_prevista(models.Model): 
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    atividade = models.CharField(max_length=200) # free text field to specify the description of the activity
    duração = models.IntegerField() # field to specify the duration of the activity in days
    observacao = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the activity
    
    def __str__(self):
        return f"Atividade Prevista {self.id} - Descrição: {self.atividade} - Duração: {self.duração} dias"

class Material(models.Model):
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    item = models.CharField(max_length=100) # free text field to specify the name of the material
    unidade = models.CharField(max_length=10) # field to specify the unit of measurement for the material
    quantidade = models.IntegerField() # field to specify the quantity of material required
    peso = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the weight of the material
    custo_unitario = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the cost of the material per unit
    valor_total = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the total cost of the material (quantidade * custo_unitario)
    terceirizado = models.BooleanField(default=False) # field to specify whether the material is outsourced or not
    observacao = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the material
    
    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="material_resumo")
    def __str__(self):
        return f"Material {self.id} - Custo: {self.valor_total}"

class Servico_terceirizado(models.Model):
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    descricao = models.CharField(max_length=100) # nome; identificacao do servico recebido
    unidade = models.CharField(max_length=10)  
    quantidade = models.DecimalField(max_digits = 10, decimal_places = 2) 
    peso = models.DecimalField(max_digits=10, decimal_places=2) 
    custo_unit = models.DecimalField(max_digits = 10, decimal_places = 2)
    valor_tot = models.DecimalField(max_digits = 10, decimal_places = 2)
    observacao = models.CharField(max_length=250)

    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="terceirizados_resumo") # link to the Resumo_orcamento entry that this MDO entry is part of, to be selected from a dropdown list of existing Resumo_orcamento entries
    def __str__(self):
        return f'Descrição: {self.descricao} - Custo total: {self.valor_tot}'

class Resumo_orcamento(models.Model):
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system 
    #fields:
    margem = models.DecimalField(max_digits = 5, decimal_places = 2) #validators=[MinValueValidator(0),MaxValueValidator(100)]
    OH = models.DecimalField(max_digits=10, decimal_places = 2)
    impostos = models.DecimalField(max_digits=5, decimal_places = 2)
    #---------------------------------------------------------------------------------
    total_MDO = models.DecimalField(max_digits=10, decimal_places = 2)
    total_material = models.DecimalField(max_digits=10, decimal_places = 2)
    total_serv_terceirizado = models.DecimalField(max_digits=10, decimal_places = 2)
    #---------------------------------------------------------------------------------
    custo_bruto = models.DecimalField(max_digits=10, decimal_places = 2)
    custo_sem_impostos = models.DecimalField(max_digits=10, decimal_places = 2)
    custo_com_impostos = models.DecimalField(max_digits=10, decimal_places = 2)

    def __str__(self):
        return f'Custo Final: {self.custo_com_impostos}'

class Orcamento(models.Model):
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    levantamento = models.OneToOneField(Levantamento, on_delete=models.CASCADE, related_name='orcamento_levantamento') # link to the Levantamento entry that contains the details of this orçamento
    #------------------------------------------------
    MDO = #list of all the N MDO entries linked to this orçamento.
    atividades_previstas = #list of all the N Ativ_prevista entries linked to this orçamento.
    materiais = #list of all the N Material entries linked to this orçamento.
    servicos_terceirizados = #list of all the N Servico_terceirizado entries linked to this orçamento.
    #------------------------------------------------
    Observacoes_setor_orcamento = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the orçamento, to be filled in the Observações section of the orçamento form
    resumo = models.OneToOneField(Resumo_orcamento, on_delete=models.CASCADE, related_name='orcamento_resumo') # link to the Resumo_orcamento entry that contains the economic summary of this orçamento

    def __str__(self):
        return f'Orçamento {self.id} - Levantamento {self.levantamento.id_orcamento} - Resumo {self.resumo.id}'
