from django.db import models

class Cliente(models.Model):
    TIPO_CHOICES = [('Fisica', 'Pessoa Física'), ('Juridica', 'Pessoa Jurídica')]
    STATUS_CHOICES = [('Ativo', 'Ativo'), ('Inativo', 'Inativo')]

    id = models.BigAutoField(primary_key=True)
    tipo = models.CharField(max_length=10, choices=TIPO_CHOICES, default='Fisica')
    razao_social = models.CharField(max_length=150) # "Razão Social / Nome Completo"
    nome_fantasia = models.CharField(max_length=150, null=True, blank=True)
    documento = models.CharField(max_length=20, unique=True) # CPF ou CNPJ
    inscricao_estadual = models.CharField(max_length=20, null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='Ativo')
    contato_geral = models.CharField(max_length=255) 
    endereco_completo = models.TextField()
    data_cadastro = models.DateField(auto_now_add=True)
    usuario_responsavel = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'Razão Social: {self.razao_social}'


class Negocio(models.Model):
    id = models.BigAutoField(primary_key=True)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE, related_name='negocios')
    empresa_prestadora = models.CharField(max_length=100) 
    nome_negocio = models.CharField(max_length=200) 
    solicitante = models.CharField(max_length=150)
    cargo = models.CharField(max_length=100, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=254)
    data_solicitacao = models.DateField(auto_now_add=True)
    data_prevista_inicio = models.DateField(null=True, blank=True)
    data_prevista_final = models.DateField(null=True, blank=True)
    arquivo_documento = models.FileField(upload_to='documentos_negocios/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nome_negocio} - {self.cliente.razao_social}"

class Servico(models.Model):
    id = models.BigAutoField(primary_key=True)
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, related_name='servicos')
    tipo_servico = models.CharField(max_length=100) 
    categoria = models.CharField(max_length=100)    
    local_execucao = models.CharField(max_length=150) 
    descricao = models.TextField()                 
    embarcacao = models.CharField(max_length=100)
    porto = models.CharField(max_length=100, null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.tipo_servico} - {self.embarcacao}"
    
class User(models.Model):
    user_email = models.CharField(max_length=150, primary_key=True)
    user_name = models.CharField(max_length=200)
    user_funcao = models.CharField(max_length=100)
    user_setor = models.CharField(max_length=100)
    user_data_nascimento = models.DateField()
    
    def __str__(self):
        return f"E-mail: {self.user_email} - Nome: {self.user_name} - Função: {self.user_funcao} - Setor: {self.user_setor}"

#--------------------- Orçamento ------------------

class Levantamento(models.Model):
    #External not displayed attributes:
    id_orcamento = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
        #auto-fill / pulled from another table entry
    cliente = models.ForeignKey(Cliente, editable=False, on_delete=models.CASCADE, related_name='orcamentos') # client id listed on selected negocio entry , auto-filled from negocio data
    negocio = models.ForeignKey(Negocio, editable=False, on_delete=models.CASCADE, related_name='orcamentos') # negocio id which this orcamento is about, to be selected from a dropdown list of existing negocio entries
    solicitante = models.ForeignKey(User, editable=False, on_delete=models.PROTECT, related_name='orcamentos') # user name logged in and creating the orcamento, auto-filled from user data
    responsavel_comercial = models.CharField(max_length=150, blank=True, null=True) # responsavel_comercial listed on selected negocio entry, auto-filled from negocio data
        #manual-fill on page
    dados_servicos = models.TextField(max_length=1000,blank=True, null=True) # free text field for any additional notes or comments about the serviço
    arquivos_negocio = models.FileField(upload_to='arquivos_negocio/', blank=True, null=True) # file upload field for attaching relevant documents or files related to the negócio

    Resumo_orcamento_link = models.OneToOneField('Resumo_orcamento', on_delete=models.CASCADE, related_name='levantamento_resumo', null=True, blank=True) # link to the Resumo_orcamento entry that contains the economic summary of this orçamento
    def __str__(self):
        return f"Orçamento {self.id_orcamento} - Negócio {self.negocio.id} - Solicitante: {self.solicitante.user_name}"

class MDO(models.Model): #Mão de obra
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    função = models.CharField(max_length=100) # free text field to specify the role or function of the labor
    quantidade = models.IntegerField() # field to specify the quantity of labor units required
    dias = models.IntegerField() # field to specify the number of days required for the labor
    custo = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the cost of the labor per unit per day
    valor_total = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the total cost of the labor (quantidade * dias * custo)
    observação = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the labor
    
    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="mao_de_obra_resumo") # link to the Resumo_orcamento entry that this MDO entry is part of, to be selected from a dropdown list of existing Resumo_orcamento entries
    def __str__(self):
        return f"Mão de Obra {self.id} - Custo: {self.valor_total}"

class Ativ_prevista(models.Model): #NAB
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    descrição = models.CharField(max_length=200) # free text field to specify the description of the activity
    quantidade = models.IntegerField() # field to specify the quantity of activity units required
    custo_unitario = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the cost of the activity per unit
    valor_total = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the total cost of the activity (quantidade * custo_unitario)
    observação = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the activity
    
    def __str__(self):
        return f"Atividade Prevista {self.id} - Custo: {self.valor_total}"

class Material(models.Model):
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    nome_material = models.CharField(max_length=100) # free text field to specify the name of the material
    unidade = models.CharField(max_length=10) # field to specify the unit of measurement for the material
    quantidade = models.IntegerField() # field to specify the quantity of material required
    custo_unitario = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the cost of the material per unit
    valor_total = models.DecimalField(max_digits=10, decimal_places=2) # field to specify the total cost of the material (quantidade * custo_unitario)
    observação = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the material
    
    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="materiais_resumo")
    def __str__(self):
        return f"Material {self.id} - Custo: {self.valor_total}"

class Servicos_terceirizados(models.Model):
    #External not displayed attributes:
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system
    #Structure
    descricao = models.CharField(max_length=100) # nome; identificacao do servico recebido
    unidade = models.CharField(max_length=10)  #Pra que isso? o campo existe nas imagens do slide
    quantidade = models.DecimalField(max_digits = 10, decimal_places = 2) #validador de valores maximos e minimos?
    custo_unit = models.DecimalField(max_digits = 10, decimal_places = 2)
    valor_tot = models.DecimalField(max_digits = 10, decimal_places = 2)
    observacoes = models.CharField(max_length=250)

    resumo = models.ForeignKey('Resumo_orcamento', on_delete=models.CASCADE, related_name="terceirizados_resumo") # link to the Resumo_orcamento entry that this MDO entry is part of, to be selected from a dropdown list of existing Resumo_orcamento entries
    def __str__(self):
        return f'Descrição: {self.descricao} - Custo total: {self.valor_tot}'

class Observacoes_setor_orcamento(models.Model):
    #External not displayed attributes:
    refecencia_orcamento = models.ForeignKey(Levantamento, on_delete=models.CASCADE, related_name='observacoes_orcamento') # reference to the orçamento entry which this observation is about, to be selected from a dropdown list of existing orçamento entries
    #Structure
    observacao = models.TextField(blank=True, null=True) # free text field for any additional notes or comments about the orçamento
    
    def __str__(self):
        return f'Observação: {self.observacao}'

class Resumo_orcamento(models.Model):
    id = models.BigAutoField(primary_key=True) # This entry id, auto-generated by the system 
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, related_name='orcamento_negocio') # reference to the negócio entry which this orçamento is about, to be selected from a dropdown list of existing negócio entries
    #fields:
    margem = models.DecimalField(max_digits = 5, decimal_places = 2) #validators=[MinValueValidator(0),MaxValueValidator(100)]
    impostos_perc = models.DecimalField(max_digits=5, decimal_places = 2)
    subtotal = models.DecimalField(max_digits=10, decimal_places = 2)
    impostos = models.DecimalField(max_digits=10, decimal_places = 2)
    custo_final = models.DecimalField(max_digits=10, decimal_places = 2)

    def __str__(self):
        return f'Custo Final: {self.custo_final}'

