# Generated by Django 6.0.3 on 2026-05-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('action', models.CharField(choices=[('alocar', 'Alocar'), ('desalocar', 'Desalocar')], max_length=20)),
                ('kind', models.CharField(choices=[('gases', 'Gases'), ('equipamentos', 'Equipamentos'), ('materiais', 'Materiais'), ('alugaveis', 'Alugáveis'), ('outros', 'Outros')], max_length=30)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('os_id', models.CharField(blank=True, max_length=150)),
                ('os_label', models.CharField(blank=True, max_length=255)),
                ('item_label', models.CharField(max_length=255)),
                ('tabela_nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('gas_nome', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('data_baixa', models.DateField()),
                ('tabela_nome', models.CharField(max_length=100)),
                ('item_label', models.CharField(max_length=255)),
                ('status_anterior', models.CharField(blank=True, max_length=100)),
                ('motivo', models.TextField(blank=True)),
                ('os_id', models.CharField(blank=True, max_length=150)),
                ('os_label', models.CharField(blank=True, max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('service_os', models.CharField(blank=True, max_length=150)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_baixa', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=60)),
                ('values', models.JSONField(default=dict)),
                ('search_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('gas_nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('service_os', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fornecedor_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_gas', to='AlmoxarifadoApp.itemestoque')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TabelaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('EQUIPAMENTOS ELETRICOS', 'EQUIPAMENTOS ELETRICOS'), ('EXTENSÃO-CABOS', 'EXTENSÃO-CABOS'), ('BOMBA HIDROJATO', 'BOMBA HIDROJATO'), ('INSTRUMENTOS', 'INSTRUMENTOS'), ('FERRAMENTAS', 'FERRAMENTAS'), ('TALHAS', 'TALHAS'), ('Controle de ferramentas', 'Controle de ferramentas'), ('Materiais', 'Materiais'), ('Alugados - Gases', 'Alugados - Gases'), ('Alugados - Equipamentos', 'Alugados - Equipamentos')], max_length=100)),
                ('workspace_email', models.EmailField(blank=True, db_index=True, max_length=254)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('workspace_email', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='AlmoxarifadoApp.tabelaestoque'),
        ),
        migrations.CreateModel(
            name='TipoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('workspace_email', 'nome')},
            },
        ),
    ]
